version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /lucida-web
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /lucida-py
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      container-bases:
        patterns: ["*"]
