[project]
name = "lucida"
version = "0.1.0"
description = "Lightweight, high-performance, cross-platform ND microscopy viewer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "typer>=0.16.1",
]

[project.scripts]
lucida = "lucida.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "fsspec>=2025.7.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "pytest>=9.0.2",
    "zarr>=3.1.2",
]
