[package]
name = "lucida-render-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "lucida-render-shell"
path = "src/main.rs"

[dependencies]
lucida-render-wgpu = { path = "../lucida-render-wgpu" }
winit = { workspace = true }
