// `FetchError` lets the source own classification; `RetryPolicy`
// makes the retry rule injectable. `classifyFetchError` is the catch-
// block boundary that promotes/wraps non-FetchError throws.

import { debugLog } from "../../debug/logging.ts";
import type { FailureDescriptor } from "../../failureContract.ts";

/**
 * - `permanent`: same failure on retry — record + surface, no retry.
 * - `transient`: network blip / timeout — eligible for retry.
 * - `pending`: generated bytes not ready yet — silent cleanup, no failure entry.
 * - `abort`: caller cancelled — silent cleanup, no failure entry.
 */
export type FetchErrorKind = "permanent" | "transient" | "pending" | "abort";

export class FetchError extends Error {
  readonly kind: FetchErrorKind;
  /**
   * True when the source itself answered the request with a failure — a
   * `source_chunk_status` frame — rather than the client giving up locally
   * (timeout, disconnect, abort). Such a failure feeds the delivery-failure
   * streak regardless of its `kind`: a source that keeps reporting failures
   * must surface even when each report is individually retryable, whereas an
   * ordinary client-side transient stays streak-exempt so a connection blip
   * cannot masquerade as a dead source. Independent of retry classification.
   */
  readonly serverReported: boolean;
  /** Stable protocol cause when the server supplied one. */
  readonly failure: FailureDescriptor | null;

  constructor(
    message: string,
    opts: {
      kind: FetchErrorKind;
      serverReported?: boolean;
      failure?: FailureDescriptor | null;
      cause?: unknown;
    },
  ) {
    super(message, opts.cause !== undefined ? { cause: opts.cause } : undefined);
    this.kind = opts.kind;
    this.serverReported = opts.serverReported ?? false;
    this.failure = opts.failure ? { ...opts.failure } : null;
    this.name = "FetchError";
  }
}

/**
 * Map an arbitrary throw into a `FetchError`. Untyped errors are conservatively
 * retryable and logged for migration; display text never determines category.
 */
export function classifyFetchError(err: unknown): FetchError {
  if (err instanceof FetchError) {
    return err;
  }
  if (err instanceof DOMException && err.name === "AbortError") {
    return new FetchError(err.message || "Aborted", { kind: "abort", cause: err });
  }
  if (err instanceof Error) {
    debugLog("cache", "cache.untyped_fetch_error", {
      message: err.message,
      classifiedAs: "transient",
    });
    return new FetchError(err.message, { kind: "transient", cause: err });
  }
  return new FetchError(String(err), { kind: "transient", cause: err });
}

/** `attempt` is the zero-based count of attempts already made. */
export interface RetryPolicy {
  shouldRetry(err: FetchError, attempt: number): boolean;
  delayMs(attempt: number): number;
}

export class OnceTransientRetry implements RetryPolicy {
  private readonly delay: number;

  constructor(delay: number) {
    this.delay = delay;
  }

  shouldRetry(err: FetchError, attempt: number): boolean {
    return err.kind === "transient" && attempt < 1;
  }

  delayMs(_attempt: number): number {
    return this.delay;
  }
}

/** TickCoordinator resubmits on the next plan tick if still wanted. */
export class NeverRetry implements RetryPolicy {
  shouldRetry(_err: FetchError, _attempt: number): boolean {
    return false;
  }

  delayMs(_attempt: number): number {
    return 0;
  }
}
